### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'input_dtype'

### ISSUE THREAD

**Issue by vchouksey** [nikicc/twitter-emotion-recognition#1]
getting error while running command "model = EmotionPredictor(classification='ekman', setting='mc')"

**Comment by nikicc** [comment]
Can you post the whole stack trace? Which version of Keras are you using? The code was only tested with `keras==1.1.0` so other versions might cause issues.

**Comment by vchouksey** [comment]
Keras==1.1.0
tensorflow==1.0.0
tensorflow-tensorboard==0.1.6
Theano==0.10.0

Also your emotion predictor code, line number ->self.model.layers[0].input eras does not able to read model first layers hence throw error as 
<img width="1107" alt="keras error" src="https://user-images.githubusercontent.com/6507341/30954869-12f3468a-a432-11e7-9600-d00d4e65799f.png">

self.classification = ekman
   self.setting = mc
   self.use_unison_model = True
   self.model = self._get_model()
   self.embeddings_model = self._get_embeddings_model()
   self.char_to_ind = self._get_char_mapping()
   self.class_values = self._get_class_values()
   self.max_len = self._get_max_sequence_length()

def _get_model(self):
   self._loaded_model_filename = ‘models/{}{}-{}.h5’.format(
       ‘unison-’ if self.use_unison_model else ‘’,
       self.classification,
       self.setting,
   )
   return load_model(self._loaded_model_filename)

def _get_embeddings_model(self):
   last_layer_output = K.function([self.model.layers[0].input,
                                   K.learning_phase()],
                                  [self.model.layers[-3].output])
   return lambda x: last_layer_output([x, 0])[0]

**Comment by vchouksey** [comment]
Thanks Final got success

**Comment by nikicc** [comment]
@vchouksey how did you solved it? Just in case, someone else stumbles upon the same issue.

**Comment by VinodPathak** [comment]
Hi, I am facing the same issue. Can you tell how did you solve it?
I have tested on keras=1.1.0, tensorflow backend=1.2.1, tried in python2 and python3.

**Comment by VinodPathak** [comment]
I solved the issue:-
keras=1.1.0
theano=0.9.0

I am searching, if this works with tensorflow backend?

**Comment by nikicc** [comment]
@VinodPathak, I’ve never tried it with Tensorflow. Let me know how this goes if you try it out.
