### ISSUE TITLE
running demo.py with error ValueError: Unknown layer: Merge

### ISSUE THREAD

**Issue by liusong299** [nikicc/twitter-emotion-recognition#10]
I tried to run the demo.py but meet the error "ValueError: Unknown layer: Merge"
my current keras version is 2.3.1-0 
How could I use this model in keras 2 ?

**Comment by nikicc** [comment]
@liusong299 sorry, I missed this. The code was only tested with `Keras==1.1.0` and I assume it does not work with 2.3.1-0. See the requirements file: https://github.com/nikicc/twitter-emotion-recognition/blob/master/requirements.txt.
