### ISSUE TITLE
Package emotion_predictor is unavailable

### ISSUE THREAD

**Issue by AmanKabra** [nikicc/twitter-emotion-recognition#13]
Colab says the package emotion_predictor is unavailable for download/load. Could you help me here?

**Comment by nikicc** [comment]
@AmanKabra `emotion_predictor` is not on pypi, hence I guess this is why Colab says it's unavailable. You'll need to clone this repository manually, but I'm not sure how to do this in Colab.

**Comment by AmanKabra** [comment]
Niki, thanks a ton for the code. I have cloned it to colab. This is such a useful package that you might want to share it to pypi!

Thanks again!

**Comment by nikicc** [comment]
@AmanKabra you're welcome. Yes, will try to find the time to push it to pypi.
