### ISSUE TITLE
What is the setting parameter while choosing model?

### ISSUE THREAD

**Issue by Akshar-code** [nikicc/twitter-emotion-recognition#17]
Hi,
I wanted to wanted to know whats the difference between ml and mc in the setting parameter? 
![Screenshot 2021-02-22 at 11 09 42 AM](https://user-images.githubusercontent.com/59618640/108667001-78ac3900-74fe-11eb-84bb-991b143ce854.png)

**Comment by nikicc** [comment]
@Akshar-code hi! `mc` stands for multiclass, while `ml` stands for multilabel. Briefly, in multiclass, only _one_ (the most prevalent) emotion is detected, while in multilabel a classifier can detect _multiple_ emotions in the same tweet. For more details check [this CrossValidated post](https://stats.stackexchange.com/questions/11859/what-is-the-difference-between-multiclass-and-multilabel-problem).

I'm closing this issue for now, but feel free to post more questions or reopen if you have more questions about it.
