### ISSUE TITLE
Layers used in unison-ekman-mc.h5

### ISSUE THREAD

**Issue by khairiyah98** [nikicc/twitter-emotion-recognition#18]
Hi, may I know what are the exact settings used for the layers in the best performing character based model i.e. unison-ekman-mc.h5? Is the following description correct?

1.	Input layer 
2.	Embedding layer (character embedding dimensions: 25)
3.	Dropout layer with rate 0.2 
4.	LSTM layer with 400 memory units, single directional
5.	LSTM layer with 400 memory units, bidirectional
6.	Merge layer
7.	Dropout layer with 800 output nodes, rate 0.5
8.	Dense layer with 6 output nodes, with softmax activation

**Comment by nikicc** [comment]
@khairiyah98 yes, that is mostly correct. Just to clarify more, and make sure this is what you had in mind: step 5. is not bidirectional, but is only single directional going backwards. So step 4. is 400 units LSTM going forward; and step 5. is 400 LSTM units going backwards.
