### ISSUE TITLE
Unrecognized keyword arguments error in defining the model

### ISSUE THREAD

**Issue by jojo101793** [nikicc/twitter-emotion-recognition#19]
Hi, when I run the following script in jupyterlab, the value error occurs. I am wondering how to fix it.

# Predictor for Ekman's emotions in multiclass setting.
model = EmotionPredictor(classification='ekman', setting='mc')

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-8795b11f6c09> in <module>
      1 # Predictor for Ekman's emotions in multiclass setting.
----> 2 model = EmotionPredictor(classification='ekman', setting='mc')

~/twitter-emotion-recognition/emotion_predictor.py in __init__(self, classification, setting, use_unison_model)
     28         self.setting = setting
     29         self.use_unison_model = use_unison_model
---> 30         self.model = self._get_model()
     31         self.embeddings_model = self._get_embeddings_model()
     32         self.char_to_ind = self._get_char_mapping()

~/twitter-emotion-recognition/emotion_predictor.py in _get_model(self)
     40             self.setting,
     41         )
---> 42         return load_model(self._loaded_model_filename)
     43 
     44     def _get_embeddings_model(self):

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py in load_model(filepath, custom_objects, compile, options)
    204       if (h5py is not None and
    205           (isinstance(filepath, h5py.File) or h5py.is_hdf5(filepath))):
--> 206         return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
    207                                                 compile)
    208 

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py in load_model_from_hdf5(filepath, custom_objects, compile)
    181       raise ValueError('No model found in config file.')
    182     model_config = json_utils.decode(model_config.decode('utf-8'))
--> 183     model = model_config_lib.model_from_config(model_config,
    184                                                custom_objects=custom_objects)
    185 

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/model_config.py in model_from_config(config, custom_objects)
     62                     '`Sequential.from_config(config)`?')
     63   from tensorflow.python.keras.layers import deserialize  # pylint: disable=g-import-not-at-top
---> 64   return deserialize(config, custom_objects=custom_objects)
     65 
     66 

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py in deserialize(config, custom_objects)
    171   """
    172   populate_deserializable_objects()
--> 173   return generic_utils.deserialize_keras_object(
    174       config,
    175       module_objects=LOCAL.ALL_OBJECTS,

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    352 
    353       if 'custom_objects' in arg_spec.args:
--> 354         return cls.from_config(
    355             cls_config,
    356             custom_objects=dict(

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in from_config(cls, config, custom_objects)
   2259     # be constructed for FunctionalModel
   2260     from tensorflow.python.keras.engine import functional  # pylint: disable=g-import-not-at-top
-> 2261     return functional.Functional.from_config(
   2262         config, custom_objects=custom_objects)
   2263 

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py in from_config(cls, config, custom_objects)
    666         ValueError: In case of improperly formatted config dict.
    667     """
--> 668     input_tensors, output_tensors, created_layers = reconstruct_from_config(
    669         config, custom_objects)
    670     model = cls(inputs=input_tensors, outputs=output_tensors,

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py in reconstruct_from_config(config, custom_objects, created_layers)
   1273   # First, we create all layers and enqueue nodes to be processed
   1274   for layer_data in config['layers']:
-> 1275     process_layer(layer_data)
   1276   # Then we process nodes in order of layer depth.
   1277   # Nodes that cannot yet be processed (if the inbound node

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py in process_layer(layer_data)
   1255       from tensorflow.python.keras.layers import deserialize as deserialize_layer  # pylint: disable=g-import-not-at-top
   1256 
-> 1257       layer = deserialize_layer(layer_data, custom_objects=custom_objects)
   1258       created_layers[layer_name] = layer
   1259 

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py in deserialize(config, custom_objects)
    171   """
    172   populate_deserializable_objects()
--> 173   return generic_utils.deserialize_keras_object(
    174       config,
    175       module_objects=LOCAL.ALL_OBJECTS,

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    358                 list(custom_objects.items())))
    359       with CustomObjectScope(custom_objects):
--> 360         return cls.from_config(cls_config)
    361     else:
    362       # Then `cls` may be a function returning a class.

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py in from_config(cls, config)
    718         A layer instance.
    719     """
--> 720     return cls(**config)
    721 
    722   def compute_output_shape(self, input_shape):

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/input_layer.py in __init__(self, input_shape, batch_size, dtype, input_tensor, sparse, name, ragged, **kwargs)
    116       input_shape = batch_input_shape[1:]
    117     if kwargs:
--> 118       raise ValueError('Unrecognized keyword arguments:', kwargs.keys())
    119 
    120     if sparse and ragged:

ValueError: ('Unrecognized keyword arguments:', dict_keys(['input_dtype']))

**Comment by nikicc** [comment]
@jojo101793 given this:
> /opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py in load_model(filepath, custom_objects, compile, options)

I suspect you are might be using TensorFlow as a backend, while these models work with Theano. Check [requirements.txt](https://github.com/nikicc/twitter-emotion-recognition/blob/master/requirements.txt#L10) for exact versions of all dependencies, and make sure to [set Theano as a backend](https://stackoverflow.com/questions/42177658/how-to-switch-backend-with-keras-from-tensorflow-to-theano).
