### ISSUE TITLE
Stop words

### ISSUE THREAD

**Issue by Akshar-code** [nikicc/twitter-emotion-recognition#20]
Hii,
I wanted to know if its better to remove stopwords before dumping the data into the models?
or is it better to use the whole sentence?

Please let me know

**Comment by nikicc** [comment]
@Akshar-code no need for any preprocessing. Just dump the whole thing in.

Our models work on characters hence we pass the whole tweet without any preprocessing as an input to the RNN.

**Comment by Akshar-code** [comment]
i just removed the hashtags and mentions, so i think it shouldnt be a problem. Where can i have a look at the training data? Atleast a peek

**Comment by nikicc** [comment]
@Akshar-code unfortunately I cannot disclose the training data. Sorry for that. For a peak, check the paper (link is in the readme), there are a few examples there.

**Comment by Akshar-code** [comment]
Hi,
I skimmed through your paper and it was great. I was wondering how we can host this code on google collab, im getting some errors doing the same

**Comment by nikicc** [comment]
@Akshar-code I'm not that familiar with the goole collab, but check the Binder link in the Readme.md. It should take you to a running Jupiter notebook.
