### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by giulianoformisano** [nikicc/twitter-emotion-recognition#21]
@nikicc Could you please help me with this?

When specifying the model:
`model = EmotionPredictor(classification='ekman', setting='mc', use_unison_model=True)`

I retrieve this error:
`AttributeError: 'str' object has no attribute 'decode'`

Please find a screenshot of the issue:
![Schermata 2021-03-11 alle 11 13 02](https://user-images.githubusercontent.com/60297728/110771416-c218ba00-825a-11eb-8430-cc32ad6fe4d1.png)

What do you think the issue might be? Thank you.

**Comment by nikicc** [comment]
@giulianoformisano not really sure what this could be. The first thing I would check is if all the dependencies are exactly at the versions as specified in the [requirements.txt](https://github.com/nikicc/twitter-emotion-recognition/blob/master/requirements.txt) file.

**Comment by giulianoformisano** [comment]
Thanks a lot for your input, @nikicc. I checked and all the dependencies are at the versions specified in the requirements.txt file. However, the issue persists.

Is there anything else that I could try? Thank you.

**Comment by giulianoformisano** [comment]
@nikicc, we have solved the issue - thanks to @niklasstoehr!

Installing h5py fixed the issue:
`!pip install 'h5py==2.10.0' --force-reinstall`

**Comment by nikicc** [comment]
@giulianoformisano happy that you fixed it and thanks for posting the fix here for others 🚀
