### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by xfgavin** [nikicc/twitter-emotion-recognition#29]
Hi there,

Thank you for this great library.

I wonder what tensorflow is used in this version of the library? I installed the newest one but it seemed to mess up with other required libraries.

Meanwhile, is it a better idea to put tensorflow version into requirements.txt?

**Comment by nikicc** [comment]
Hi @xfgavin!

> I wonder what tensorflow is used in this version of the library? I installed the newest one but it seemed to mess up with other required libraries.

No, the code uses Theano backend, not Tensorflow. See [requirements file](https://github.com/nikicc/twitter-emotion-recognition/blob/master/requirements.txt#L10) for exact versions and make sure you set the backed to Theano in Keras (e.g. check [the demo script](https://github.com/nikicc/twitter-emotion-recognition/blob/master/demo.py#L1-L2) for how we do it there).

> Meanwhile, is it a better idea to put tensorflow version into requirements.txt?

Not sure we can do that, as the models that are saved in the repo are in Theano format, and I'm not sure transforming them to Tensorflow is a trivial task?

**Comment by xfgavin** [comment]
Thank you.

I was running the code on databricks, not sure if it was because the environ code didn't work?
Any hints on how to use it on databricks?

**Comment by xfgavin** [comment]
OK, I made it working, just need to place environ call before importing the model.

**Comment by nikicc** [comment]
@xfgavin happy to hear you could make it work.
