### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by BrittaRude** [nikicc/twitter-emotion-recognition#31]
Hi, 

I am trying to installl the package, but am not sure how. I tried *pip install* and *pip install git* but I get an error message. Could you maybe help me out here? 

Thank you and Best, 
Britta

**Comment by nikicc** [comment]
Hi @BrittaRude!

Unfortunately, this package is not on pip 😏  You would need:
* to clone the repository into a local file system,
* go into the root folder (i.e. [this folder](https://github.com/nikicc/twitter-emotion-recognition))
* run `pip install -r requirements.txt` to install all the dependencies
* run `python demo.py` to run our example script.

Hope this helps, let me know how it goes or if you have more questions.
