### ISSUE TITLE
Environment Setup Error

### ISSUE THREAD

**Issue by ccjustin** [nikicc/twitter-emotion-recognition#37]
Hi! I'm new to making issues on Git, so I apologize in advance for any lapses in etiquette in this post. I'm having a lot of trouble trying to set up the model for use in a university project. I wanted to run the demo first, so after cloning the repository and initializing an environment, I run "pip3 install -r requirements.txt". When installing pandas, the "Getting requirements to build wheel" stage exits with an error : ModuleNotFoundError: No module named 'numpy'. I was able to reproduce this error on a peer's device, so it doesn't seem to be an issue with my Python environment, but I'm not entirely sure. How might this issue be addressed? 
![Screen Shot 2024-04-01 at 11 48 48 PM](https://github.com/nikicc/twitter-emotion-recognition/assets/116770157/9fc5f709-9943-4e49-879c-29b3539da956)

**Comment by nikicc** [comment]
It seems like numpy, [which is one of the requirements](https://github.com/nikicc/twitter-emotion-recognition/blob/master/requirements.txt#L3), is missing. Can you check if numpy got installed or not?

**Comment by ccjustin** [comment]
Hi:

I realized that I could switch the Python version to something that was more compatible with the dependencies outlined in the requirements.txt. Namely, 3.7.17 All the packages now install correctly, but I get one issue. My code is as shown:

`from emotion_predictor import EmotionPredictor 

def predict(text):
    model = EmotionPredictor(classification='ekman', setting='mc', use_unison_model=True)
    predictions = model.predict_probabilities([text])
    # unison_emotions = {} 
    print("debugging unison emotions")
    print(predictions)

def main():
    predict("i'm drinking strawberry lemonade")

if __name__ == "__main__":
    main()`

This is just some dummy code to make sure the model works on my device. However, when running it, I get this big ValueError about a shape needing to have rank 0, and I'm not sure what that means. Could you clarify this for me? How might I address this issue? Is it my usage of the model? Thank you so much :   ) 

![Screen Shot 2024-04-01 at 11 48 48 PM](https://github.com/nikicc/twitter-emotion-recognition/assets/116770157/6001710d-2bd3-417d-b46f-22d42ed885e7)

**Comment by nikicc** [comment]
> However, when running it, I get this big ValueError about a shape needing to have rank 0, and I'm not sure what that means. Could you clarify this for me? How might I address this issue? Is it my usage of the model? 

Can you paste the stack trace for this error? The image that you pasted seems the same as before (it's about numpy).

**Comment by ccjustin** [comment]
Sorry! I was working late last night and I pasted the wrong picture... Here's a screencap of the stack trace. "unison.py" is running the code from the previous comment. I was wondering if this had something to do with the tensorflow version I have installed. After the requirements.txt was installed succesfully, I ran the program, and initially got an error since tensorflow wasn't installed. I installed a version I found to be compatible, namely tensorflow v1.15.0, but I'm not sure if that's what's compatible with the model. 

Let me know if the text is too small. 
![Screen Shot 2024-04-03 at 2 09 24 PM](https://github.com/nikicc/twitter-emotion-recognition/assets/116770157/ff41676b-c7e9-4789-ab41-c8f56db7791f)

**Comment by nikicc** [comment]
> I was wondering if this had something to do with the tensorflow version I have installed. After the requirements.txt was installed succesfully, I ran the program, and initially got an error since tensorflow wasn't installed. I installed a version I found to be compatible, namely tensorflow v1.15.0, but I'm not sure if that's what's compatible with the model.

Oh, this is the problem. This code needs Theano, not Tensorflow! See how you can swap the Keras backend here: https://github.com/nikicc/twitter-emotion-recognition/blob/master/demo.py#L1-L2

**Comment by ccjustin** [comment]
I missed that, thank you so much for your help and patience!

**Comment by nikicc** [comment]
Glad we managed to fix it :)
