### ISSUE TITLE
Trained RNN models

### ISSUE THREAD

**Issue by dharathakkar5** [nikicc/twitter-emotion-recognition#4]
How did you train the models? Did you publish the paper yet? Can you share some ideas?

**Comment by nikicc** [comment]
@dharathakkar5 the paper just got accepted today 🎉 IIUC the preprint will be available on journal's website in few weeks. As soon as it is, I'll link it here.

**Comment by dharathakkar5** [comment]
Thanks and Congratulations. Looking forward to it.

**Comment by nikicc** [comment]
@dharathakkar5 here is the preprint of the paper: http://ieeexplore.ieee.org/document/8295234/
