### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'python'

### ISSUE THREAD

**Issue by SidShenoy** [nikicc/twitter-emotion-recognition#5]
Whenever I try to execute the following statement:

model = EmotionPredictor(classification='ekman', setting='mc')

I get the above-mentioned error. Please resolve.

![image](https://user-images.githubusercontent.com/18630586/37558293-8dec57f6-2a37-11e8-93b0-01dcf3fff374.png)

**Comment by faizankhan29** [comment]
I am getting the same error,please resolve.

**Comment by nikicc** [comment]
Not sure what the error is, but it looks like something related to tensorflow. The code from this repo is meant to be run on Theano, not tensoflow. Check [requirements.txt file](https://github.com/nikicc/twitter-emotion-recognition/blob/master/requirements.txt)

**Comment by SidShenoy** [comment]
simply upgrade keras
pip3 install --upgrade keras
this should do it.

**Comment by basitanwer** [comment]
Upgraded keras. Now I am getting the following error

`ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("embedding_1/random_uniform:0", shape=(412, 25), dtype=float32)'`

**Comment by basitanwer** [comment]
Problem solved. I just had to change the backend to `theano`

For linux go to `$HOME/.keras/keras.json`

and change the backend value from `tensorflow`

```json
{
    "image_data_format": "channels_last",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "tensorflow"
}
