### ISSUE TITLE
Incompatibility with new keras

### ISSUE THREAD

**Issue by sabidhasan** [nikicc/twitter-emotion-recognition#6]
It seems like this package is no longer compatible with the new version of keras (which is included with Tensorflow). I am unable to run with Python 3.6, both on and off anaconda

**Comment by nikicc** [comment]
@sabidhasan I haven't tried it with the new version of Keras. Can you try with the versions which are specified in the [requirements.txt](https://github.com/nikicc/twitter-emotion-recognition/blob/master/requirements.txt) file?

**Comment by lcarnevale** [comment]
The versions specified in the requirements.txt require tensorflow installed. Last version (1.12.0) raises this exception:
`AttributeError: module 'tensorflow' has no attribute 'python'`

What is the tensorflow version used for your project?

**Comment by nikicc** [comment]
@lcarnevale Theano was used for this project, not Tensorflow. Can you try with `keras==1.1.0` & `theano==0.8.2` as I'm not sure whether it works or not with other versions. Also, keep in mind that you might need to configure Keras to use the Theano backend and not the Tensorflow.

**Comment by lcarnevale** [comment]
> @lcarnevale Theano was used for this project, not Tensorflow. Can you try with `keras==1.1.0` & `theano==0.8.2` as I'm not sure whether it works or not with other versions. Also, keep in mind that you might need to configure Keras to use the Theano backend and not the Tensorflow.

Because of a Numpy Theano incompatibility, `theano==0.8.2` raises the following exception:
`AttributeError: ('The following error happened while compiling the node', DotModulo(A, s, m, A2, s2, m2), '\n', "module 'numpy.core.multiarray' has no attribute '_get_ndarray_c_version'")`

Your application is working for me with this configuration:
```
h5py==2.9.0
Keras==1.1.0
numpy==1.16.0
pandas==0.24.1
python-dateutil==2.8.0
pytz==2018.9
PyYAML==3.13
scipy==1.2.1
six==1.12.0
Theano==1.0.4
```

Many thanks for your help.

**Comment by nikicc** [comment]
Great to hear that! And thanks for posting the env config that works for you, it might be helpful to others.

**Comment by grafixoner** [comment]
I can get it to run in 1.2.2.  However I'm wondering can you upgrade these to work or release the training code so we can get v2 keras models?

**Comment by nebupulickal** [comment]
@lcarnevale i am  getting an error after installing the packages mentioned
Using Theano backend.
Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    model = EmotionPredictor(classification='ekman', setting='mc', use_unison_model=True)
  File "/home/pi/Desktop/twitter-emotion-recognition-master/emotion_predictor.py", line 31, in __init__
    self.model = self._get_model()
  File "/home/pi/Desktop/twitter-emotion-recognition-master/emotion_predictor.py", line 43, in _get_model
    return load_model(self._loaded_model_filename)
  File "/home/pi/.virtualenvs/emotionnew/lib/python3.5/site-packages/keras/models.py", line 120, in load_model
    import h5py
  File "/home/pi/.virtualenvs/emotionnew/lib/python3.5/site-packages/h5py/__init__.py", line 26, in <module>
    from . import _errors
ImportError: libhdf5_serial.so.100: cannot open shared object file: No such file or directory

**Comment by nikicc** [comment]
@grafixoner not sure I can tackle that any time soon, sorry. If you got it to work in 1.2.2 than you should be able to see all the trained weights, which can probably be transfered into newest version somehow.

**Comment by nikicc** [comment]
@nebupulickal can you try with exactly the version that @lcarnevale posted in above comment. IIUC using that versions should work.

**Comment by nebupulickal** [comment]
@nikicc solved the issue :)... Install the package libhdf5-100
_sudo apt install libhdf5-100_

**Comment by nebupulickal** [comment]
@nikicc thanku :)

**Comment by nikicc** [comment]
@nebupulickal happy to hear that!

**Comment by alanj250** [comment]
When i executed the code demo.py in ubuntu 18.0.4 , its not running with theano. It gives using tensorflow as backend and throwing error no module named tensorflow. How is it possible to execute the code using theano in ubuntu 18.0.4.. set the environment as given in this loop above.

**Comment by alanj250** [comment]
Can anyone help me with the version of ubuntu the code is working. Will this work in python 3

**Comment by nikicc** [comment]
@alanj250 check this for how to set the backend Keras will use: https://stackoverflow.com/questions/42177658/how-to-switch-backend-with-keras-from-tensorflow-to-theano

Also, it will work in python 3.

**Comment by alanj250** [comment]
@nikicc thank u... It worked... Is it possible to make it work with latest keras and tensorflow backend ?

**Comment by nikicc** [comment]
@alanj250 probably possible, but I think it's not trivial. Let me know how it will go if you decide to try it.

**Comment by sabidhasan** [comment]
If you want I can take a stab at porting it to the latest version of TF,
and I'll make a PR.

Abid

**Comment by grafixoner** [comment]
That would be cool, I was gonna tackle doing the same at some point.  

Looking forward to the pull request!

**Comment by alanj250** [comment]
@sabidhasan waiting for that. Thanku to all

**Comment by akarsh30** [comment]
Hi can anyone please tell me the sequence in which the files needed to be run?
ALso when i am running demo.py this error is being raised. Please help
![Screenshot (150)](https://user-images.githubusercontent.com/41483461/56880539-d4304b80-6a7a-11e9-9f0c-d340bdfc3e56.png)
![Screenshot (151)](https://user-images.githubusercontent.com/41483461/56880540-d4304b80-6a7a-11e9-8c64-b053516b9794.png)

**Comment by nikicc** [comment]
@akarsh30 are you sure you have the right version of the dependencies? Check [requirements.txt](https://github.com/nikicc/twitter-emotion-recognition/blob/master/requirements.txt) file.

**Comment by willyjospel** [comment]
@akarsh30 set everything correctly.

**Comment by akarsh30** [comment]
> @akarsh30 are you sure you have the right version of the dependencies? Check [requirements.txt](https://github.com/nikicc/twitter-emotion-recognition/blob/master/requirements.txt) file.


Yes I have keras 1.1.0
and Theano 0.8.2

**Comment by willyjospel** [comment]
you can mail @ willyjospel@gmail.com the error screenshot.

**Comment by akarsh30** [comment]
I am getting this error. How can I fix it?
![Screenshot (154)](https://user-images.githubusercontent.com/41483461/56941639-6ac04380-6b33-11e9-9710-c764b63dbe5c.png)

**Comment by nikicc** [comment]
@akarsh30 not really sure, but the fact that there is the name `tensorflow` in the exception message suggests, that you might be using Tensorflow backend instead of Theano. 

Check these and make sure you're running Keras with Theano backend and not Tensorflow:
* https://stackoverflow.com/questions/42177658/how-to-switch-backend-with-keras-from-tensorflow-to-theano
* https://keras.io/backend/

**Comment by lilanleo** [comment]
> Hi can anyone please tell me the sequence in which the files needed to be run?
> ALso when i am running demo.py this error is being raised. Please help
> ![Screenshot (150)](https://user-images.githubusercontent.com/41483461/56880539-d4304b80-6a7a-11e9-9f0c-d340bdfc3e56.png)
> ![Screenshot (151)](https://user-images.githubusercontent.com/41483461/56880540-d4304b80-6a7a-11e9-8c64-b053516b9794.png)

Same error of unknow layer: Merge, how did you fix it? I'm sure I got every dependencies right and python==3.6

**Comment by polsci** [comment]
Based on this thread and particularly @lcarnevale's helpful comment https://github.com/nikicc/twitter-emotion-recognition/issues/6#issuecomment-467891717  I've got a working repo that will work with Binder with a notebook to run the code in demo.py-  see https://github.com/polsci/twitter-emotion-recognition
Have made a pull request:
https://github.com/nikicc/twitter-emotion-recognition/pull/11

**Comment by nikicc** [comment]
Yes, thanks to @polsci the `requirements.txt` was updated so hopefully there will be fewer issues with the dependencies. Also, the Binder link is now added in the `README.md` file.

I think I can now close this issue, but if issues still persist for someone feel free to re-open.
