### ISSUE TITLE
ValueError: Unknown layer: Merge

### ISSUE THREAD

**Issue by t855001** [nikicc/twitter-emotion-recognition#8]
I am getting this error when I run demo.py.

Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py:1109: UserWarning: Update your `InputLayer` call to the Keras 2 API: `InputLayer(batch_input_shape=[None, 143..., name="input_1", sparse=False, dtype="float32")`
  return cls(**config)
/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py:1109: UserWarning: The `dropout` argument is no longer support in `Embedding`. You can apply a `keras.layers.SpatialDropout1D` layer right after the `Embedding` layer to get the same behavior.
  return cls(**config)
/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py:1109: UserWarning: Update your `Embedding` call to the Keras 2 API: `Embedding(output_dim=25, input_dtype="int32", name="embedding_1", mask_zero=False, trainable=True, batch_input_shape=[None, Non..., input_dim=412, activity_regularizer=None, input_length=None, embeddings_initializer="uniform", embeddings_regularizer=None, embeddings_constraint=None)`
  return cls(**config)
/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py:1109: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(name="dropout_1", trainable=True, rate=0.2)`
  return cls(**config)
/usr/local/lib/python3.6/dist-packages/keras/layers/recurrent.py:2298: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  return cls(**config)
/usr/local/lib/python3.6/dist-packages/keras/layers/recurrent.py:2298: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(name="lstm_1", stateful=False, batch_input_shape=[None, Non..., input_dtype="float32", trainable=True, activation="tanh", unroll=False, return_sequences=False, go_backwards=False, unit_forget_bias=True, input_shape=(None, 25), units=400, kernel_initializer="glorot_uniform", recurrent_initializer="orthogonal", recurrent_activation="hard_sigmoid", kernel_regularizer=None, bias_regularizer=None, recurrent_regularizer=None, dropout=0.0, recurrent_dropout=0.0, implementation=0)`
  return cls(**config)
/usr/local/lib/python3.6/dist-packages/keras/layers/recurrent.py:2150: UserWarning: `implementation=0` has been deprecated, and now defaults to `implementation=1`.Please update your layer call.
  warnings.warn('`implementation=0` has been deprecated, '
/usr/local/lib/python3.6/dist-packages/keras/layers/recurrent.py:2298: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(name="lstm_2", stateful=False, batch_input_shape=[None, Non..., input_dtype="float32", trainable=True, activation="tanh", unroll=False, return_sequences=False, go_backwards=True, unit_forget_bias=True, input_shape=(None, 25), units=400, kernel_initializer="glorot_uniform", recurrent_initializer="orthogonal", recurrent_activation="hard_sigmoid", kernel_regularizer=None, bias_regularizer=None, recurrent_regularizer=None, dropout=0.0, recurrent_dropout=0.0, implementation=0)`
  return cls(**config)
Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    model = EmotionPredictor(classification='ekman', setting='mc', use_unison_model=True)
  File "/home/aso/mas_code/twitter-emotion-recognition-master/emotion_predictor.py", line 30, in __init__
    self.model = self._get_model()
  File "/home/aso/mas_code/twitter-emotion-recognition-master/emotion_predictor.py", line 42, in _get_model
    return load_model(self._loaded_model_filename)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: Merge

**Comment by nikicc** [comment]
@t855001 it seems that you're using the TensorFlow backend while the models in this repo were trained using Theano backend and hence do not work with TensorFlow.

Make sure to install the dependencies that are specified in the [requirements.txt](https://github.com/nikicc/twitter-emotion-recognition/blob/master/requirements.txt) file. Then, also make sure you configure Keras to use the Theano backend and not TensorFlow; see https://stackoverflow.com/questions/42177658/how-to-switch-backend-with-keras-from-tensorflow-to-theano

I'm closing this as I'm pretty sure that it should work with the right version of the requirements and Theano backend. If you still have issues, feel free to reopen.

**Comment by t855001** [comment]
@nikicc  Thank you for answering, 

I changed backend to Theano.

But I am getting this error.

/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using Theano backend.
/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/engine/base_layer.py:1109: UserWarning: Update your `InputLayer` call to the Keras 2 API: `InputLayer(batch_input_shape=[None, 143..., name="input_1", sparse=False, dtype="float32")`
  return cls(**config)
/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/engine/base_layer.py:1109: UserWarning: The `dropout` argument is no longer support in `Embedding`. You can apply a `keras.layers.SpatialDropout1D` layer right after the `Embedding` layer to get the same behavior.
  return cls(**config)
/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/engine/base_layer.py:1109: UserWarning: Update your `Embedding` call to the Keras 2 API: `Embedding(output_dim=25, input_dtype="int32", name="embedding_1", mask_zero=False, trainable=True, batch_input_shape=[None, Non..., input_dim=412, activity_regularizer=None, input_length=None, embeddings_initializer="uniform", embeddings_regularizer=None, embeddings_constraint=None)`
  return cls(**config)
/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/engine/base_layer.py:1109: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(name="dropout_1", trainable=True, rate=0.2)`
  return cls(**config)
/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/layers/recurrent.py:2298: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  return cls(**config)
/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/layers/recurrent.py:2298: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(name="lstm_1", stateful=False, batch_input_shape=[None, Non..., input_dtype="float32", trainable=True, activation="tanh", unroll=False, return_sequences=False, go_backwards=False, unit_forget_bias=True, input_shape=(None, 25), units=400, kernel_initializer="glorot_uniform", recurrent_initializer="orthogonal", recurrent_activation="hard_sigmoid", kernel_regularizer=None, bias_regularizer=None, recurrent_regularizer=None, dropout=0.0, recurrent_dropout=0.0, implementation=0)`
  return cls(**config)
/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/layers/recurrent.py:2150: UserWarning: `implementation=0` has been deprecated, and now defaults to `implementation=1`.Please update your layer call.
  warnings.warn('`implementation=0` has been deprecated, '
/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/layers/recurrent.py:2298: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(name="lstm_2", stateful=False, batch_input_shape=[None, Non..., input_dtype="float32", trainable=True, activation="tanh", unroll=False, return_sequences=False, go_backwards=True, unit_forget_bias=True, input_shape=(None, 25), units=400, kernel_initializer="glorot_uniform", recurrent_initializer="orthogonal", recurrent_activation="hard_sigmoid", kernel_regularizer=None, bias_regularizer=None, recurrent_regularizer=None, dropout=0.0, recurrent_dropout=0.0, implementation=0)`
  return cls(**config)
Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    model = EmotionPredictor(classification='ekman', setting='mc', use_unison_model=True)
  File "/Applications/mas_code/twitter-emotion-recognition-master/emotion_predictor.py", line 30, in __init__
    self.model = self._get_model()
  File "/Applications/mas_code/twitter-emotion-recognition-master/emotion_predictor.py", line 42, in _get_model
    return load_model(self._loaded_model_filename)
  File "/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/engine/network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/Users/beta/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: Merge

My environment:
Theano==1.0.4
Keras==2.2.4
pandas==0.21.1

**Comment by nikicc** [comment]
@t855001 Keras should be at version `keras==1.1.0` not 2.2.4; see [requirements.txt](https://github.com/nikicc/twitter-emotion-recognition/blob/master/requirements.txt) file. I suggest you uninstall Keras and install `keras==1.1.0`.

**Comment by t855001** [comment]
Thank you,

I succeeded.
